#Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
y_train

array([6, 5, 6, ..., 5, 5, 6])

In [ ]:
y_test

array([5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 7,
       6, 7, 5, 7, 7, 5, 4, 4, 5, 6, 6, 5, 6, 6, 6, 7, 6, 6, 7, 6, 6, 6,
       6, 6, 5, 6, 7, 7, 6, 7, 5, 5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5,
       7, 3, 5, 7, 6, 6, 8, 5, 5, 5, 6, 6, 7, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       5, 7, 5, 5, 5, 5, 5, 6, 6, 4, 5, 5, 7, 6, 6, 5, 5, 7, 6, 6, 5, 6,
       6, 6, 6, 6, 5, 6, 6, 7, 7, 3, 5, 4, 6, 6, 5, 6, 6, 5, 5, 5, 5, 4,
       5, 6, 5, 4, 5, 7, 7, 5, 6, 6, 5, 7, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 7, 6, 6, 5, 6, 5, 5, 5,
       5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 7, 5, 5, 7, 7, 5, 5, 6, 6,
       6, 6, 5, 6, 5, 6, 7, 6, 7, 5, 5, 6, 7, 5, 5, 5, 5, 7, 5, 5, 5, 8,
       5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 7, 5, 5, 5, 5, 7, 5, 6, 6, 6, 5,
       6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 4, 5,
       4, 5, 6, 6, 6, 7, 6, 7, 6, 5, 5, 7, 6, 5, 6, 6, 5, 8, 6, 5, 6, 7,
       7, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 6, 7, 6, 7,

In [ ]:
x_train

array([[ 6.9 ,  0.49,  0.19, ...,  3.38,  0.64,  9.8 ],
       [ 7.  ,  0.49,  0.49, ...,  3.34,  0.76, 10.5 ],
       [ 8.9 ,  0.32,  0.31, ...,  3.17,  0.55, 10.4 ],
       ...,
       [12.1 ,  0.4 ,  0.52, ...,  3.03,  0.66, 10.2 ],
       [ 6.5 ,  0.52,  0.11, ...,  3.34,  0.52,  9.3 ],
       [ 7.3 ,  0.51,  0.18, ...,  3.52,  0.73,  9.5 ]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [ ]:
ntrain

array([[6],
       [5],
       [6],
       ...,
       [5],
       [5],
       [6]])

In [ ]:

ntest

array([[5],
       [6],
       [6],
       [5],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [7],
       [6],
       [7],
       [5],
       [7],
       [7],
       [5],
       [4],
       [4],
       [5],
       [6],
       [6],
       [5],
       [6],
       [6],
       [6],
       [7],
       [6],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [6],
       [5],
       [6],
       [7],
       [7],
       [6],
       [7],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [7],
       [3],
       [5],
       [7],
       [6],
       [6],
       [8],
       [5],
       [5],
       [5],
       [6],
       [6],
       [7],
       [6],
       [5],
       [5],
       [6],
    

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [ ]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [ ]:
xn_train

array([[-0.80190452, -0.22275448, -0.40968398, ...,  0.4326351 ,
        -0.09089563, -0.57897048],
       [-0.74455196, -0.22275448,  1.12273698, ...,  0.17333787,
         0.61084789,  0.07767035],
       [ 0.34514674, -1.16339359,  0.20328441, ..., -0.92867536,
        -0.61720327, -0.01613548],
       ...,
       [ 2.18042874, -0.72073989,  1.27597907, ..., -1.83621567,
         0.02606162, -0.20374715],
       [-1.03131477, -0.05675935, -0.81832956, ...,  0.17333787,
        -0.79263915, -1.04799964],
       [-0.57249427, -0.11209106, -0.46076467, ...,  1.3401754 ,
         0.43541201, -0.86038798]])

In [ ]:
xn_test

array([[-0.45778914, -0.16742277,  0.4586879 , ...,  0.23816217,
         0.8447624 ,  0.07767035],
       [-0.0563212 ,  1.16053831, -0.92049096, ..., -0.21560798,
        -0.50024602,  1.29714617],
       [ 0.34514674, -0.55474475,  0.91841418, ...,  0.23816217,
         0.25997613,  1.953787  ],
       ...,
       [-0.40043658, -0.11209106, -0.15428048, ...,  1.01605387,
         0.02606162, -0.76658214],
       [-0.22837889,  1.96284814, -1.22697515, ...,  0.30298648,
        -1.90373305, -1.23561131],
       [-0.0563212 ,  0.33056264, -1.38021725, ...,  1.21052679,
        -0.032417  , -1.04799964]])

In [ ]:
yn_train

array([[ 0.45865149],
       [-0.776328  ],
       [ 0.45865149],
       ...,
       [-0.776328  ],
       [-0.776328  ],
       [ 0.45865149]])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [ ]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [ ]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [ ]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [ ]:

from sklearn.metrics import r2_score

In [ ]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [ ]:
print(r, l, d, s, p)

0.49337196106472303 0.37443112071098605 -0.0333533237994188 0.3839415443688049 0.37443112071098583
